slam_toolbox:
  ros__parameters:
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    mode: mapping 

    use_sim_time: false 
    
    map_file_name: /home/hosbot/ros2_ws/src/hospital_robot/maps/hospital_map
    map_start_pose: [0.0, 0.0, 0.0]
    
    resolution: 0.05            
    max_laser_range: 12.0

    minimum_time_interval: 1.0  
    
    transform_timeout: 0.2
    tf_buffer_duration: 30.
    stack_size_to_use: 40000000 # 40MB buffer
    enable_interactive_mode: true